apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki-cache
  name: {{ .Release.Name }}-fuseki-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fuseki-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fuseki-cache
        project: zbmed
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: ts-nfdi4cat
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - image: varnish
          name: {{ .Release.Name }}-fuseki-cache
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/varnish/default.vcl
              name: config-volume
              subPath: default.vcl
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: varnish-default.vcl
                path: default.vcl
            name: {{ .Release.Name }}-fuseki-cache-config
          name: config-volume
