apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki
  name: {{ .Release.Name }}-fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fuseki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fuseki
        project: zbmed
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: ts-nfdi4cat
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - args:
            - --config=/fuseki/config/skosmos.ttl
          env:
            - name: JAVA_OPTIONS
              value: -Xmx2g -Xms1g
          image: {{ .Values.backend.image }}
          name: {{ .Release.Name }}-fuseki
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 3030
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /fuseki/config
            - name: data-storage
              mountPath: /fuseki/databases
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-fuseki-config
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-fuseki-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-fuseki-pvc
  labels:
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts-nfdi4cat
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-version-pvc
  labels:
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts-nfdi4cat
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi