apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki-cache-config
  name: {{ .Release.Name }}-fuseki-cache-config
data:
  varnish-default.vcl: |
    vcl 4.0;

    backend default {
        .host = "{{ .Release.Name }}-fuseki";
        .port = "3030";
    }

    sub vcl_backend_response {
        # store for a long time (1 week)
        set beresp.ttl = 1w;
        # always gzip before storing, to save space in the cache
        set beresp.do_gzip = true;
    }

