apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fuseki
  name: fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fuseki
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fuseki
    spec:
      containers:
        - args:
            - --config=/fuseki/skosmos.ttl
          env:
            - name: JAVA_OPTIONS
              value: -Xmx2g -Xms1g
          image: ghcr.io/zbmed/skosmos/fuseki:4.8.0
          name: fuseki
          ports:
            - containerPort: 3030
              protocol: TCP
          volumeMounts:
            - mountPath: /fuseki/skosmos.ttl
              name: fuseki-cm0
              subPath: skosmos.ttl
      hostname: fuseki
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: skosmos.ttl
                path: skosmos.ttl
            name: fuseki-cm0
          name: fuseki-cm0
