apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: skosmos
  name: skosmos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: skosmos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: skosmos
    spec:
      containers:
        - image: ghcr.io/zbmed/skosmos/skosmos:latest
          name: skosmos
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/config.ttl
              name: skosmos-cm0
              subPath: config.ttl
      hostname: skosmos
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config-docker-compose.ttl
                path: config.ttl
            name: skosmos-cm0
          name: skosmos-cm0
