{{- if .Values.ingress.dns }}
{{- $relname := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{ if .Values.ingress.enableSSL }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: {{ .Values.ingress.certIssuer | quote}}
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    {{- if .Values.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.auth.secretName }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ingress.appRoot }}
spec:
  {{ if .Values.ingress.enableSSL }}
  tls:
    - hosts:
        - {{ .Values.ingress.dns }}
      secretName: {{ .Release.Name }}-ssl-secret
  {{ end }}
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: 80
{{- end }}

---

{{- if .Values.ingress.dns }}
{{- $relname := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-redirect
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: {{ .Values.ingress.appRoot }}/
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: {{ .Values.ingress.appRoot }}
            pathType: Exact
            backend:
              service:
                name: redirect-dummy
                port:
                  number: 80
{{- end }}