apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ts-nfdi4cat
    app.kubernetes.io/component: ui
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
