apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki
  name: {{ .Release.Name }}-fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fuseki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fuseki
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - args:
            - --config=/fuseki/config/skosmos.ttl
          env:
            - name: JAVA_OPTIONS
              value: -Xmx2g -Xms1g
          image: ghcr.io/zbmed/skosmos/fuseki:5.3.0
          name: {{ .Release.Name }}-fuseki
          ports:
            - containerPort: 3030
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /fuseki/config
            - name: data-storage
              mountPath: /fuseki/databases
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-fuseki-config
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-fuseki-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-fuseki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi