apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki
  name: {{ .Release.Name }}-fuseki
spec:
  ports:
    - name: "fuseki"
      port: 9030
      targetPort: 3030
  selector:
    app: {{ .Release.Name }}-fuseki
