apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fuseki-cache
  name: fuseki-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fuseki-cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fuseki-cache
    spec:
      containers:
        - image: varnish
          name: fuseki-cache
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/varnish/default.vcl
              name: fuseki-cache-cm0
              subPath: default.vcl
      hostname: fuseki-cache
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: varnish-default.vcl
                path: default.vcl
            name: fuseki-cache-cm0
          name: fuseki-cache-cm0
