apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki-cache
  name: {{ .Release.Name }}-fuseki-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fuseki-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fuseki-cache
    spec:
      containers:
        - image: varnish
          name: {{ .Release.Name }}-fuseki-cache
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /etc/varnish/default.vcl
              name: config-volume
              subPath: default.vcl
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: varnish-default.vcl
                path: default.vcl
            name: {{ .Release.Name }}-fuseki-cache-config
          name: config-volume
