{{- if .Values.ingress.dns }}
{{- $relname := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{ if .Values.ingress.enableSSL }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: {{ .Values.ingress.certIssuer | quote}}
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    {{- if .Values.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.auth.secretName }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end }}
spec:
  {{ if .Values.ingress.enableSSL }}
  tls:
    - hosts:
        - {{ .Values.ingress.dns }}
      secretName: {{ .Release.Name }}-ssl-secret
  {{ end }}
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: fuseki-cache
                port:
                  number: 80
{{- end }}