apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-fuseki-cache
  name: {{ .Release.Name }}-fuseki-cache
spec:
  ports:
    - name: "varnish"
      port: 9031
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-fuseki-cache
