apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
  name: {{ .Release.Name }}-frontend
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-frontend
